version: "3.9"

services:
  db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - just_net_network

  app:
    image: auth_app
    container_name: auth_app
    ports:
      - "8000:8000"
    volumes:
      - .:/home
    depends_on:
      - db
    networks:
      - just_net_network

networks:
  just_net_network: